# Learning NumPy

## 1.Basic Operation of NumPy

In [36]:
import numpy as np
# list to matrix
array = np.array([
    [1,2,3],
    [4,5,6]
])
print(array)

[[1 2 3]
 [4 5 6]]


In [37]:
# print the dimension of the array
print('dim:',array.ndim)

dim: 2


In [38]:
# print the rows and cols of the array
print('shape:',array.shape)

shape: (2, 3)


In [39]:
# print the number of elements in the array
print('size:',array.size)

size: 6


## 2.Create Arrays by NumPy

In [2]:
import numpy as np
# one dim
a = np.array([99,7,29], dtype=np.int32) # np.int equals to int32
print(a)
print(a.dtype)

[99  7 29]
int32


In [4]:
# multi dims
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [8]:
# array of zeros
a = np.zeros((3,4)) # doesn't indicate the datatype
print(a)
print(a.dtype)
b = np.zeros((3,4),dtype=np.int) # indicate the datatype
print(b)
print(b.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [6]:
# array of ones
a = np.ones((3,4))
print(a)
print(a.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [9]:
# array of null, every element in it equals a number near zero
a = np.empty((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# array of continuous numbers
a = np.arange(2,14,2) # numbers of 2-14, step length of 2，doesn't include 14
print(a)
b = np.arange(1,5,0.5) # step size can be float
print(b)
c = np.arange(6)
print(a,b,c)

[ 2  4  6  8 10 12]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 2  4  6  8 10 12] [1.  1.5 2.  2.5 3.  3.5 4.  4.5] [0 1 2 3 4 5]


In [20]:
# reshape
b = a.reshape((3,2))
print(b)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [24]:
# array of continuous numbers
a = np.linspace(1,10,10)
print(a)
b = np.linspace(1,10,9) # include end point
print(b)
c = np.linspace(1,10,9,endpoint=False) # not include end point
print(c)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [31]:
# range()
a = range(1,10,1)
print(a)
b = range(1,10,3)
print(b)

range(1, 10)
range(1, 10, 3)


## 3.Basic Computing of NumPy

### 3.1 one dim array computing

In [4]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)

[10 20 30 40] [0 1 2 3]


In [6]:
# minus
c = a - b
print(c)

[10 19 28 37]


In [7]:
# multiple
print(a*b)
print(a.dot(b))

[  0  20  60 120]
200


In [8]:
# involution
print(b**3)

[ 0  1  8 27]


In [9]:
# do math
c = np.sin(a)
print(c)

[-0.54402111  0.91294525 -0.98803162  0.74511316]


In [10]:
# compare numbers
print(b>2)

[False False False  True]


In [11]:
# if two arrays are the same
a = np.array([0,2,1,3])
print(a==b)

[ True False False  True]


###  3.2 multi dims array computing

In [15]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [17]:
# multiple of multi dims 
# first method
c = a.dot(b)
print(c)
# second method
d = np.dot(a,b)
print(d)

[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [19]:
print(np.sum(c))
print(np.min(c))
print(np.max(c))

11


In [26]:
a = np.array([[0,3,1,5],[2,1,1,7]])
print(a)
# sum of every col, let axis equal 0
print("sum1=", np.sum(a,axis=0))
# sum of every row, let axis equal 1
print("sum2=", np.sum(a,axis=1))
# find min of every col, let axis equal 0
print("min1=",np.min(a,axis=0))
print("max1=",np.max(a,axis=0))
print("min2=",np.min(a,axis=1))
print("max2=",np.max(a,axis=1))

[[0 3 1 5]
 [2 1 1 7]]
sum1= [ 2  4  2 12]
sum2= [ 9 11]
min1= [0 1 1 5]
max1= [2 3 1 7]
min2= [0 1]
max2= [5 7]
