# Learning NumPy

## 1.Basic Operation of NumPy

In [36]:
import numpy as np
# list to matrix
array = np.array([
    [1,2,3],
    [4,5,6]
])
print(array)

[[1 2 3]
 [4 5 6]]


In [37]:
# print the dimension of the array
print('dim:',array.ndim)

dim: 2


In [38]:
# print the rows and cols of the array
print('shape:',array.shape)

shape: (2, 3)


In [39]:
# print the number of elements in the array
print('size:',array.size)

size: 6


## 2.Create Arrays by NumPy

In [3]:
import numpy as np
# one dim
a = np.array([99,7,29], dtype=np.int32) # np.int equals to int32
print(a)
print(a.dtype)

[99  7 29]
int32


In [4]:
# multi dims
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [8]:
# array of zeros
a = np.zeros((3,4)) # doesn't indicate the datatype
print(a)
print(a.dtype)
b = np.zeros((3,4),dtype=np.int) # indicate the datatype
print(b)
print(b.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [6]:
# array of ones
a = np.ones((3,4))
print(a)
print(a.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [9]:
# array of null, every element in it equals a number near zero
a = np.empty((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# array of continuous numbers
a = np.arange(2,14,2) # numbers of 2-14, step length of 2，doesn't include 14
print(a)
b = np.arange(1,5,0.5) # step size can be float
print(b)

[ 2  4  6  8 10 12]


In [20]:
# reshape
b = a.reshape((3,2))
print(b)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [24]:
# array of continuous numbers
a = np.linspace(1,10,10)
print(a)
b = np.linspace(1,10,9) # include end point
print(b)
c = np.linspace(1,10,9,endpoint=False) # not include end point
print(c)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [31]:
# range()
a = range(1,10,1)
print(a)
b = range(1,10,3)
print(b)

range(1, 10)
range(1, 10, 3)


## 3.Basic Calculating of NumPy